server.port=3000

spring.datasource.url=jdbc:oracle:thin:@//oracle-dev:1521/XEPDB1
spring.datasource.username=fidel
spring.datasource.password=Fidel_2024
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.initialization-fail-timeout=0
